# Generated by Django 5.2.4 on 2025-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgesource",
            name="processed_text",
            field=models.TextField(blank=True),
        ),
    ]
