# Generated by Django 5.2.4 on 2025-07-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistants", "0002_knowledgesource_processed_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="microservice_assistant_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assistant",
            name="microservice_vector_store_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
